---
title: "Kaggle R Markdown Train Test Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
```

Column {.sidebar}
-----------------------------------------------------------------------


```{r}
setwd('C:\\Users\\Philippe\\workspace\\shinyfun\\shinyfun')
train = read.csv('train.csv')

selectInput('xcol', 'X Variable', names(train))
    
selectInput('ycol', 'Y Variable', names(train),
                selected=names(train)[[2]])
    
numericInput('clusters', 'Cluster count', 3,
              min = 1, max = 9)
```

Column 
-----------------------------------------------------------------------
### K Means

```{r}
palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",
  "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999"))

# Combine the selected variables into a new data frame
selectedData <- reactive({
  train[, c(input$xcol, input$ycol)]
})

clusters <- reactive({
  kmeans(selectedData(), input$clusters)
})

renderPlot({
  par(mar = c(5.1, 4.1, 0, 1))
  plot(selectedData(),
       col = clusters()$cluster,
       pch = 20, cex = 3)
  points(clusters()$centers, pch = 4, cex = 4, lwd = 4)
})
```

Column
-----------------------------------------------------------------------

```{r}
library(knitr)
kable(train)
```